### ISSUE TITLE
Dateiliste fehlerhaft

### ISSUE THREAD

**Issue by MinIsMin** [doctorluk/ULX-CSS-Checker#3]
Deine (riesige) Dateiliste scheint ein paar Dateien zu enthalten, welche in CS:S Installationen nicht existieren.
Einmal ist es bei einem Freund aufgetreten; Er hat die CS:S Daten und alles funktioniert.
Leider weiß ich nicht mehr welche Datei es war, jedoch eine mit "brick" im Namen.

Es wäre nötig, die Dateiliste zu aktualisieren, um keine Spieler zu kicken, obwohl sie die CS:S Daten haben.

**Comment by doctorluk** [comment]
Ich habe einen recht beliebten Server und habe eine Übersicht der Dateien erstellt, die bei mir existieren, wenn ich CS:S frisch von Steam installiere. Bisher sind dort maximal zwei Fälle bekannt, in denen Dateien als fehlend interpretiert werden, diese aber nicht fehlen.
Optimal wäre es, wenn nur Texturen, Models und Sounds getestet werden, die von Nöten sind, aber das ist denke ich eine utopische Aufgabe diese zu finden.
Du darfst mir gerne eine Dateiliste zur Verfügung stellen (sollte recht flott gehen mit ein wenig Google und einer Batch Datei) der Person, die das Problem hat. Ein Vergleich sollte ja machbar sein.

**Comment by MinIsMin** [comment]
Deine CS:S Liste ist aktuell, bei meinem Freund fehlen ein paar Dateien.

Vielen Dank für deine Hilfe.
